# Robot Configuration Parameters
#acc_lim_x: 0.1
#acc_lim_y: 2.5
#acc_lim_th: 0.05
max_vel_x: 0.1
min_vel_x: 0.03
max_rotational_vel: 0.25
min_in_place_rotational_vel: 0.05
escape_vel: -0.04
holonomic_robot: false

# Goal Tolerance Parameters
#xy_goal_tolerance: 0.15
#yaw_goal_tolerance: 0.36
#latch_xy_goal_tolerance: false 

# Forward Simulation Parameters
sim_time: 20.0
#sim_granularity: 0.25
#angular_sim_granularity: 0.025
#vx_samples: 2
#vtheta_samples: 10

# Trajectory Scoring Parameters
goal_distance_bias: 1.5
path_distance_bias: 1.0
#occdist_scale: 0.2
#heading_lookahead: 1.5
dwa: true
#prune_plan: true

# Oscillation Prevention Parameters
# default was 0.05
oscillation_reset_dist: 0.50
