global_frame: /map #/odom_wheel_frame #/cata_odom_combined_frame # /map
robot_base_frame: /base_link
update_frequency: 4.0
publish_frequency: 4.0
static_map: false
rolling_window: true
width: 20.0
height: 20.0
resolution: 0.05

